addre more info in yaml

diff --git a/.github/workflows/deploy-to-astro.yaml b/.github/workflows/deploy-to-astro.yaml
--- a/.github/workflows/deploy-to-astro.yaml
+++ b/.github/workflows/deploy-to-astro.yaml
@@ -4,7 +4,7 @@ on:
   workflow_dispatch:
     inputs:
       deploymentId:
-        description: "cm3jcbtvh0rrb01pk97u196sm"
+        description: "Deployment ID"
         required: true
         type: string
       apiToken:
@@ -14,14 +14,39 @@ on:
   push:
     branches:
       - main
+      - dev
+      - feature/*
 
 env:
   ASTRO_API_TOKEN: ${{ inputs.apiToken || secrets.ASTRO_API_TOKEN }}
-  DEPLOYMENT_ID: ${{ inputs.deploymentId || vars.DEPLOYMENT_ID }}
+  DEPLOYMENT_ID: ${{ inputs.deploymentId || secrets.DEPLOYMENT_ID }}
 
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-    - name: Deploy to Astro
-      uses: astronomer/deploy-action@v0.4
+      - name: Validate Inputs
+        run: |
+          if [ -z "${{ env.ASTRO_API_TOKEN }}" ]; then
+            echo "Error: ASTRO_API_TOKEN is not set."
+            exit 1
+          fi
+          if [ -z "${{ env.DEPLOYMENT_ID }}" ]; then
+            echo "Error: DEPLOYMENT_ID is not set."
+            exit 1
+          fi
+
+      - name: Deploy to Astro
+        uses: astronomer/deploy-action@v0.4
+        with:
+          deployment_id: ${{ env.DEPLOYMENT_ID }}
+          api_key: ${{ env.ASTRO_API_TOKEN }}
+          force_deploy: true  # Optional
+
+      - name: Notify on Success
+        if: success()
+        run: echo "Deployment to Astronomer successful!"
+
+      - name: Notify on Failure
+        if: failure()
+        run: echo "Deployment to Astronomer failed!"
